import {
  Users,
  User,
  UserCog,
  Smartphone,
  Globe,
  Shield,
  AppWindow,
  Zap,
  Database,
  Archive,
  Mail,
  RefreshCw,
  Key,
  Target,
  Settings,
  AlertTriangle,
  LayoutGrid,
  TrendingUp,
  Monitor,
  Layers,
  Cpu,
  BarChart2,
  ShieldCheck,
  Network,
  Server,
  ArrowDownCircle,
  CheckSquare,
  Calendar,
  Terminal,
  Box,
  GitBranch,
  Activity,
  FileText,
  Share2,
  Cloud,
  Code2,
  Workflow,
  GraduationCap,
  Package,
  Atom,
  DatabaseBackup,
  Lock,
  Bell,
  Building2,
  Upload,
  Filter,
} from 'lucide-react';
import { ElementType } from 'react';
import {
  FaChartLine,
  FaClipboardList,
  FaCog,
  FaCreditCard,
  FaEnvelope,
  FaMobileAlt,
  FaRegFileAlt,
  FaSms,
  FaUserShield,
  FaUsers,
  FaGithub,
} from 'react-icons/fa';
import {
  SiAngular,
  SiMongodb,
  SiNginx,
  SiNodedotjs,
  SiRedis,
  SiPostgresql,
  SiReact,
  SiFastapi,
  SiNextdotjs,
  SiApacheairflow,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiGrafana,
} from 'react-icons/si';

import { ArchitectureIconKey } from '../types/architecture.types';

export const ARCHITECTURE_ICONS: Record<ArchitectureIconKey, ElementType> = {
  // Lucide React Icons
  Users,
  User,
  UserCog,
  Smartphone,
  Globe,
  Shield,
  AppWindow,
  Zap,
  Database,
  Archive,
  Mail,
  RefreshCw,
  Key,
  Target,
  Settings,
  AlertTriangle,
  LayoutGrid,
  TrendingUp,
  Monitor,
  Layers,
  Cpu,
  BarChart2,
  ShieldCheck,
  Network,
  Server,
  ArrowDownCircle,
  CheckSquare,
  Calendar,
  Terminal,
  Box,
  GitBranch,
  Activity,
  FileText,
  Share2,
  Cloud,
  Code2,
  Workflow,
  GraduationCap,
  Package,
  Atom,
  DatabaseBackup,
  Lock,
  Bell,
  Building2,
  Upload,
  Filter,

  // DevelUp string mappings
  user: User,
  graduate: GraduationCap,
  users: Users,
  database: Database,
  file: FileText,
  cache: DatabaseBackup,
  cloud: Cloud,
  server: Server,
  package: Package,
  jwt: Key,
  lock: Lock,
  role: ShieldCheck,
  github: FaGithub,
  bell: Bell,
  analytics: Activity,

  // LeadSquared/MathCo specific mappings
  cylinder: Database,
  DatabaseZap: Database,

  // Wipro (React Icons)
  FaChartLine,
  FaClipboardList,
  FaCog,
  FaCreditCard,
  FaEnvelope,
  FaMobileAlt,
  FaRegFileAlt,
  FaSms,
  FaUserShield,
  FaUsers,

  // Simple Icons — brand / tech logos
  SiAngular,
  SiMongodb,
  SiNginx,
  SiNodedotjs,
  SiRedis,
  SiPostgresql,
  SiReact,
  SiFastapi,
  SiNextdotjs,
  SiApacheairflow,
  // AWS services — using lucide equivalents (no Si AWS icons in installed version)
  SiAmazonaws: Cloud,
  SiAmazons3: Archive,
  SiAmazonredshift: Database,
  SiAmazondynamodb: Database,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiGrafana,
};
