import {
  Users,
  User,
  UserCog,
  Smartphone,
  Globe,
  Shield,
  AppWindow,
  Zap,
  Database,
  Archive,
  Mail,
  RefreshCw,
  Key,
  Target,
  Settings,
  AlertTriangle,
  LayoutGrid,
  TrendingUp,
  Monitor,
  Layers,
  Cpu,
  BarChart2,
  ShieldCheck,
  Network,
  Server,
  ArrowDownCircle,
  CheckSquare,
  Calendar,
  Terminal,
  Box,
  GitBranch,
  Activity,
  FileText,
  Share2,
  Cloud,
  Code2,
  Workflow,
  GraduationCap,
  Package,
  Atom,
  DatabaseBackup,
  Lock,
  Bell,
  Building2,
  Upload,
  Filter,
} from 'lucide-react';
import { ElementType } from 'react';
import {
  FaChartLine,
  FaClipboardList,
  FaCog,
  FaCreditCard,
  FaEnvelope,
  FaMobileAlt,
  FaRegFileAlt,
  FaSms,
  FaUserShield,
  FaUsers,
  FaGithub,
} from 'react-icons/fa';
import {
  SiAngular,
  SiMongodb,
  SiNginx,
  SiNodedotjs,
  SiRedis,
  SiPostgresql,
  SiReact,
  SiFastapi,
  SiNextdotjs,
  SiApacheairflow,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiGrafana,
} from 'react-icons/si';

import { ArchitectureIconKey } from '../types/architecture.types';

export const ARCHITECTURE_ICONS: Record<ArchitectureIconKey, ElementType> = {
  // Lucide React Icons
  Users: Users,
  User: User,
  UserCog: UserCog,
  Smartphone: Smartphone,
  Globe: Globe,
  Shield: Shield,
  AppWindow: AppWindow,
  Zap: Zap,
  Database: Database,
  Archive: Archive,
  Mail: Mail,
  RefreshCw: RefreshCw,
  Key: Key,
  Target: Target,
  Settings: Settings,
  AlertTriangle: AlertTriangle,
  LayoutGrid: LayoutGrid,
  TrendingUp: TrendingUp,
  Monitor: Monitor,
  Layers: Layers,
  Cpu: Cpu,
  BarChart2: BarChart2,
  ShieldCheck: ShieldCheck,
  Network: Network,
  Server: Server,
  ArrowDownCircle: ArrowDownCircle,
  CheckSquare: CheckSquare,
  Calendar: Calendar,
  Terminal: Terminal,
  Box: Box,
  GitBranch: GitBranch,
  Activity: Activity,
  FileText: FileText,
  Share2: Share2,
  Cloud: Cloud,
  Code2: Code2,
  Workflow: Workflow,
  GraduationCap: GraduationCap,
  Package: Package,
  Atom: Atom,
  DatabaseBackup: DatabaseBackup,
  Lock: Lock,
  Bell: Bell,
  Building2: Building2,
  Upload: Upload,
  Filter: Filter,

  // DevelUp string mappings
  user: User,
  graduate: GraduationCap,
  users: Users,
  database: Database,
  file: FileText,
  cache: DatabaseBackup,
  cloud: Cloud,
  server: Server,
  package: Package,
  jwt: Key,
  lock: Lock,
  role: ShieldCheck,
  github: FaGithub,
  bell: Bell,
  analytics: Activity,

  // LeadSquared/MathCo specific mappings
  cylinder: Database,
  DatabaseZap: Database,

  // Wipro (React Icons)
  FaChartLine: FaChartLine,
  FaClipboardList: FaClipboardList,
  FaCog: FaCog,
  FaCreditCard: FaCreditCard,
  FaEnvelope: FaEnvelope,
  FaMobileAlt: FaMobileAlt,
  FaRegFileAlt: FaRegFileAlt,
  FaSms: FaSms,
  FaUserShield: FaUserShield,
  FaUsers: FaUsers,

  // Simple Icons — brand / tech logos
  SiAngular: SiAngular,
  SiMongodb: SiMongodb,
  SiNginx: SiNginx,
  SiNodedotjs: SiNodedotjs,
  SiRedis: SiRedis,
  SiPostgresql: SiPostgresql,
  SiReact: SiReact,
  SiFastapi: SiFastapi,
  SiNextdotjs: SiNextdotjs,
  SiApacheairflow: SiApacheairflow,
  // AWS services — using lucide equivalents (no Si AWS icons in installed version)
  SiAmazonaws: Cloud,
  SiAmazons3: Archive,
  SiAmazonredshift: Database,
  SiAmazondynamodb: Database,
  SiDocker: SiDocker,
  SiKubernetes: SiKubernetes,
  SiGithubactions: SiGithubactions,
  SiGrafana: SiGrafana,
};
